# Generated by Django 2.1 on 2018-10-22 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0002_remove_usuario_num_documento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='curso',
        ),
    ]
